//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.4952
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dis.unina.it/logbus-ng/entities")]
[System.Xml.Serialization.XmlRootAttribute("logbus-entityplugin", Namespace="http://www.dis.unina.it/logbus-ng/entities", IsNullable=false)]
public partial class EntityPluginConfiguration {
    
    private FieldType[] entitykeyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("entity-key")]
    [System.Xml.Serialization.XmlArrayItemAttribute("field", IsNullable=false)]
    public FieldType[] entitykey {
        get {
            return this.entitykeyField;
        }
        set {
            this.entitykeyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dis.unina.it/logbus-ng/entities")]
[System.Xml.Serialization.XmlRootAttribute("field", Namespace="http://www.dis.unina.it/logbus-ng/entities", IsNullable=false)]
public enum FieldType {
    
    /// <remarks/>
    host,
    
    /// <remarks/>
    process,
    
    /// <remarks/>
    logger,
    
    /// <remarks/>
    module,
    
    /// <remarks/>
    @class,
    
    /// <remarks/>
    method,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dis.unina.it/logbus-ng/entities")]
[System.Xml.Serialization.XmlRootAttribute("entity-key", Namespace="http://www.dis.unina.it/logbus-ng/entities", IsNullable=false)]
public partial class EntityKey {
    
    private FieldType[] fieldField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("field")]
    public FieldType[] field {
        get {
            return this.fieldField;
        }
        set {
            this.fieldField = value;
        }
    }
}
